"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Permit2__factory = exports.Erc20__factory = exports.AllowanceTransfer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AllowanceTransfer__factory_1 = require("./AllowanceTransfer__factory");
Object.defineProperty(exports, "AllowanceTransfer__factory", { enumerable: true, get: function () { return AllowanceTransfer__factory_1.AllowanceTransfer__factory; } });
var Erc20__factory_1 = require("./Erc20__factory");
Object.defineProperty(exports, "Erc20__factory", { enumerable: true, get: function () { return Erc20__factory_1.Erc20__factory; } });
var Permit2__factory_1 = require("./Permit2__factory");
Object.defineProperty(exports, "Permit2__factory", { enumerable: true, get: function () { return Permit2__factory_1.Permit2__factory; } });
